load:
  path: "data/train.csv"
  file_format: "csv"

preprocess:
  target_column: "label"

train:
  model_type: "RandomForestClassifier"
  model_params:
    n_estimators: 100

evaluate:
  metrics: ["accuracy", "f1"]
